[package]
name = "pixie-ui-demo"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
pixie-ui = { path = ".." }
pixie-ui-mev = { path = "../mev" }
pixie-ui-winit = { path = "../winit" }
edict = { version = "1.0.0-rc10", path = "../../edict" }
mev = { path = "../../mev" }
winit = { version = "0.30" }
